version: '3.8'

services:
  # ZooKeeper集群
  zk1:
    image: zookeeper:3.8.1
    hostname: zk1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    volumes:
      - zk1_data:/data
      - zk1_datalog:/datalog
      - ./config/zookeeper.conf:/conf/zoo.cfg

  zk2:
    image: zookeeper:3.8.1
    hostname: zk2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    volumes:
      - zk2_data:/data
      - zk2_datalog:/datalog
      - ./config/zookeeper.conf:/conf/zoo.cfg

  zk3:
    image: zookeeper:3.8.1
    hostname: zk3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    volumes:
      - zk3_data:/data
      - zk3_datalog:/datalog
      - ./config/zookeeper.conf:/conf/zoo.cfg

  # MySQL服务
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: scheduler
      MYSQL_USER: scheduler
      MYSQL_PASSWORD: scheduler123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  # Kafka集群
  kafka1:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - kafka1_data:/var/lib/kafka/data
    depends_on:
      - zk1
      - zk2
      - zk3

  kafka2:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka2
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - kafka2_data:/var/lib/kafka/data
    depends_on:
      - zk1
      - zk2
      - zk3

  kafka3:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka3
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - kafka3_data:/var/lib/kafka/data
    depends_on:
      - zk1
      - zk2
      - zk3

  # 调度器服务
  scheduler1:
    build: .
    hostname: scheduler1
    ports:
      - "8081:8080"
    environment:
      NODE_ID: scheduler1
      ZK_HOSTS: zk1:2181,zk2:2181,zk3:2181
      KAFKA_BROKERS: kafka1:29092,kafka2:29092,kafka3:29092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: scheduler
      MYSQL_PASSWORD: scheduler123
      MYSQL_DATABASE: scheduler
    volumes:
      - ./config:/etc/scheduler
    depends_on:
      - zk1
      - zk2
      - zk3
      - kafka1
      - kafka2
      - kafka3
      - mysql

  scheduler2:
    build: .
    hostname: scheduler2
    ports:
      - "8082:8080"
    environment:
      NODE_ID: scheduler2
      ZK_HOSTS: zk1:2181,zk2:2181,zk3:2181
      KAFKA_BROKERS: kafka1:29092,kafka2:29092,kafka3:29092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: scheduler
      MYSQL_PASSWORD: scheduler123
      MYSQL_DATABASE: scheduler
    volumes:
      - ./config:/etc/scheduler
    depends_on:
      - zk1
      - zk2
      - zk3
      - kafka1
      - kafka2
      - kafka3
      - mysql

  # Prometheus服务
  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./scheduler/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./scheduler/config/rules:/etc/prometheus/rules
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - scheduler1
      - scheduler2

  # Grafana服务
  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./scheduler/config/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./scheduler/config/grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  # AlertManager服务
  alertmanager:
    image: prom/alertmanager:v0.25.0
    ports:
      - "9093:9093"
    volumes:
      - ./scheduler/config/alertmanager:/etc/alertmanager
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    depends_on:
      - prometheus

  # MySQL Exporter
  mysql-exporter:
    image: prom/mysqld-exporter:v0.15.0
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=scheduler:scheduler123@(mysql:3306)/scheduler
    depends_on:
      - mysql

  # Kafka Exporter
  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    ports:
      - "9308:9308"
    command:
      - '--kafka.server=kafka1:29092'
      - '--kafka.server=kafka2:29092'
      - '--kafka.server=kafka3:29092'
    depends_on:
      - kafka1
      - kafka2
      - kafka3

volumes:
  zk1_data:
  zk1_datalog:
  zk2_data:
  zk2_datalog:
  zk3_data:
  zk3_datalog:
  kafka1_data:
  kafka2_data:
  kafka3_data:
  mysql_data:
  prometheus_data:
  grafana_data:
  alertmanager_data: 